const CHANGE_index_CMS_CATEGORY = "index/CHANGE_index_CMS_CATEGORY";
const ARTICLE_CATEGORY_LIST = "index/ARTICLE_CATEGORY_LIST";
const ARTICLE_LIST = "index/ARTICLE_LIST";
const ARRICLE_COMMENT_LIST = "index/ARRICLE_COMMENT_LIST";
export {
  CHANGE_index_CMS_CATEGORY,
  ARTICLE_CATEGORY_LIST,
  ARTICLE_LIST,
  ARRICLE_COMMENT_LIST,
};
